### PR TITLE
Deleting unecessary file: SignToolData.json

### PR DESCRIPTION
**Pull request by livarcocc**

### CODE REVIEW

**Comment by tmat** [comment]
What about the use of Microsoft402 certificate vs. Microsoft400 which is what Arcade will use by default?

**Comment by nguerrera** [comment]
How does 402 differ from 400? I don't know why we'd care.

**Comment by livarcocc** [comment]
We should be fine using whatever arcade is using.

**Comment by tmat** [comment]
OK, if you don't care than this is good enough.

**Pull request merged**
