### PR TITLE
Moving to repo toolset.

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @livarcocc

**Comment by livarcocc** [comment]
Weird that CI is failing here but passed in the other one. master and release/2.1.3xx should be the same.

**Comment by tannergooding** [comment]
There was no CI for the other branch (there is now)  and this makes modifications to the groovy, which means the jobs running aren't doing the right thing.

**Comment by tannergooding** [comment]
test ci please

**Comment by tannergooding** [comment]
https://ci.dot.net/job/dotnet_cli-migrate/job/master/job/GenPRTest/job/debug_windows_nt_x64_prtest/1/
https://ci.dot.net/job/dotnet_cli-migrate/job/master/job/GenPRTest/job/debug_ubuntu16.04_x64_prtest/1/
https://ci.dot.net/job/dotnet_cli-migrate/job/master/job/GenPRTest/job/debug_osx10.12_x64_prtest/1/

**Pull request merged**
