### PR TITLE
Moving to repo toolset.

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
test ci please

**Comment by tannergooding** [comment]
@dotnet-bot test ci please

**Comment by tannergooding** [comment]
test this please

**Comment by tannergooding** [comment]
test ci please

**Comment by tannergooding** [comment]
FYI. @mmitche 

This moves cli-migrate to repo-toolset and should unblock signing (have to merge to master and modify the vso build defintion, will do so tomorrow).

**Comment by mmitche** [comment]
@tannergooding Did the definition get modified?  Seeing some failures in the build.

**Comment by tannergooding** [comment]
Sent you a direct message on the issue. It should be resolved now.

**Pull request merged**
